name: FileTeCouch
version: 0.5.1
authors:
- Samuel BERTHE <contact@samuel-berthe.fr>
- Corentin Pillet <contact@corentin-pillet.com>
description: A Couchbase Server client library, based on CouchClient (Rikulo team), written in Dart language, for the Kordam project.
homepage: https://github.com/Kordam/FileTeCouch
environment:
  sdk: '>=1.7.2'
documentation: https://github.com/Kordam/FileTeCouch
dependencies:
  couchclient:
    git: https://github.com/samber/couchclient.git
  memcached_client:
    git: https://github.com/samber/memcached-client.git
    version: '>=0.5.5'
  yaml: 1.1.1
dev_dependencies:
  unittest: any
