name: FileTeCouch
version: 0.4.1
authors:
  - Samuel BERTHE <contact@samuel-berthe.fr>
  - Corentin PILLET <contact@corentin-pillet.com>
description: A Couchbase Server client library, based on CouchClient (Rikulo team), written in Dart language, for the Kordam project.
homepage: https://github.com/Kordam/FileTeCouch
environment:
  sdk: '>=1.7.2'
documentation: https://github.com/Kordam/FileTeCouch
dependencies:
  couchclient: any
  memcached_client: any
  yaml: 1.1.1
dev_dependencies:
  unittest: any
